language: go

jobs:
  include:
    # 64-bit ARM
    - os: linux
      go: 1.15
      arch: arm64
      env:
        - GO111MODULE=on
      script:
        - go build && go test
    # 32-bit ARM
    - os: linux
      go: 1.15
      arch: arm64
      env:
        - GO111MODULE=on
      script:
        - GOARCH=arm go build && GOARCH=arm go test
    # 64-bit x86
    - os: linux
      go: 1.15
      arch: amd64
      env:
        - GO111MODULE=on
      script:
        # 64-bit build
        - go build && go test
